package nzero.admin.record.excel;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Map;
import nzero.admin.egovframework.cmmn.util.Util;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class DevcExcel {
  private static Log log = LogFactory.getLog(DevcExcel.class);
  
  public static String devcExcelMake(String filePath, String fileName, Map<String, String> devcInfo) {
    String result = "1";
    try {
      XSSFWorkbook wb = new XSSFWorkbook();
      XSSFSheet sheet = wb.createSheet(Util.nvl(devcInfo.get("tmpRaceNumber")));
      XSSFCell c_01_A = null, c_01_B = null, c_01_C = null, c_01_D = null, c_01_E = null, c_01_F = null, c_01_G = null, c_01_H = null, c_01_I = null, c_01_J = null, c_01_K = null, c_01_L = null;
      XSSFCell c_02_A = null, c_02_B = null, c_02_C = null, c_02_D = null, c_02_E = null, c_02_F = null, c_02_G = null, c_02_H = null, c_02_I = null, c_02_J = null, c_02_K = null, c_02_L = null;
      XSSFCell c_03_A = null, c_03_B = null, c_03_C = null, c_03_D = null, c_03_E = null, c_03_F = null, c_03_G = null, c_03_H = null, c_03_I = null, c_03_J = null, c_03_K = null, c_03_L = null;
      XSSFCell c_04_A = null, c_04_B = null, c_04_C = null, c_04_D = null, c_04_E = null, c_04_F = null, c_04_G = null, c_04_H = null, c_04_I = null, c_04_J = null, c_04_K = null, c_04_L = null;
      XSSFCell c_05_A = null, c_05_B = null, c_05_C = null, c_05_D = null, c_05_E = null, c_05_F = null, c_05_G = null, c_05_H = null, c_05_I = null, c_05_J = null, c_05_K = null, c_05_L = null;
      XSSFCell c_06_A = null, c_06_B = null, c_06_C = null, c_06_D = null, c_06_E = null, c_06_F = null, c_06_G = null, c_06_H = null, c_06_I = null, c_06_J = null, c_06_K = null, c_06_L = null;
      XSSFCell c_07_A = null, c_07_B = null, c_07_C = null, c_07_D = null, c_07_E = null, c_07_F = null, c_07_G = null, c_07_H = null, c_07_I = null, c_07_J = null, c_07_K = null, c_07_L = null;
      XSSFCell c_08_A = null, c_08_B = null, c_08_C = null, c_08_D = null, c_08_E = null, c_08_F = null, c_08_G = null, c_08_H = null, c_08_I = null, c_08_J = null, c_08_K = null, c_08_L = null;
      XSSFCell c_09_A = null, c_09_B = null, c_09_C = null, c_09_D = null, c_09_E = null, c_09_F = null, c_09_G = null, c_09_H = null, c_09_I = null, c_09_J = null, c_09_K = null, c_09_L = null;
      XSSFCell c_10_A = null, c_10_B = null, c_10_C = null, c_10_D = null, c_10_E = null, c_10_F = null, c_10_G = null, c_10_H = null, c_10_I = null, c_10_J = null, c_10_K = null, c_10_L = null;
      XSSFCell c_11_A = null, c_11_B = null, c_11_C = null, c_11_D = null, c_11_E = null, c_11_F = null, c_11_G = null, c_11_H = null, c_11_I = null, c_11_J = null, c_11_K = null, c_11_L = null;
      XSSFCell c_12_A = null, c_12_B = null, c_12_C = null, c_12_D = null, c_12_E = null, c_12_F = null, c_12_G = null, c_12_H = null, c_12_I = null, c_12_J = null, c_12_K = null, c_12_L = null;
      XSSFCell c_13_A = null, c_13_B = null, c_13_C = null, c_13_D = null, c_13_E = null, c_13_F = null, c_13_G = null, c_13_H = null, c_13_I = null, c_13_J = null, c_13_K = null, c_13_L = null;
      XSSFCell c_14_A = null, c_14_B = null, c_14_C = null, c_14_D = null, c_14_E = null, c_14_F = null, c_14_G = null, c_14_H = null, c_14_I = null, c_14_J = null, c_14_K = null, c_14_L = null;
      XSSFCell c_15_A = null, c_15_B = null, c_15_C = null, c_15_D = null, c_15_E = null, c_15_F = null, c_15_G = null, c_15_H = null, c_15_I = null, c_15_J = null, c_15_K = null, c_15_L = null;
      XSSFCell c_16_A = null, c_16_B = null, c_16_C = null, c_16_D = null, c_16_E = null, c_16_F = null, c_16_G = null, c_16_H = null, c_16_I = null, c_16_J = null, c_16_K = null, c_16_L = null;
      XSSFCell c_17_A = null, c_17_B = null, c_17_C = null, c_17_D = null, c_17_E = null, c_17_F = null, c_17_G = null, c_17_H = null, c_17_I = null, c_17_J = null, c_17_K = null, c_17_L = null;
      XSSFCell c_18_A = null, c_18_B = null, c_18_C = null, c_18_D = null, c_18_E = null, c_18_F = null, c_18_G = null, c_18_H = null, c_18_I = null, c_18_J = null, c_18_K = null, c_18_L = null;
      XSSFCell c_19_A = null, c_19_B = null, c_19_C = null, c_19_D = null, c_19_E = null, c_19_F = null, c_19_G = null, c_19_H = null, c_19_I = null, c_19_J = null, c_19_K = null, c_19_L = null;
      XSSFCell c_20_A = null, c_20_B = null, c_20_C = null, c_20_D = null, c_20_E = null, c_20_F = null, c_20_G = null, c_20_H = null, c_20_I = null, c_20_J = null, c_20_K = null, c_20_L = null;
      XSSFCell c_21_A = null, c_21_B = null, c_21_C = null, c_21_D = null, c_21_E = null, c_21_F = null, c_21_G = null, c_21_H = null, c_21_I = null, c_21_J = null, c_21_K = null, c_21_L = null;
      XSSFCell c_22_A = null, c_22_B = null, c_22_C = null, c_22_D = null, c_22_E = null, c_22_F = null, c_22_G = null, c_22_H = null, c_22_I = null, c_22_J = null, c_22_K = null, c_22_L = null;
      XSSFCell c_23_A = null, c_23_B = null, c_23_C = null, c_23_D = null, c_23_E = null, c_23_F = null, c_23_G = null, c_23_H = null, c_23_I = null, c_23_J = null, c_23_K = null, c_23_L = null;
      XSSFCell c_24_A = null, c_24_B = null, c_24_C = null, c_24_D = null, c_24_E = null, c_24_F = null, c_24_G = null, c_24_H = null, c_24_I = null, c_24_J = null, c_24_K = null, c_24_L = null;
      XSSFCell c_25_A = null, c_25_B = null, c_25_C = null, c_25_D = null, c_25_E = null, c_25_F = null, c_25_G = null, c_25_H = null, c_25_I = null, c_25_J = null, c_25_K = null, c_25_L = null;
      XSSFCell c_26_A = null, c_26_B = null, c_26_C = null, c_26_D = null, c_26_E = null, c_26_F = null, c_26_G = null, c_26_H = null, c_26_I = null, c_26_J = null, c_26_K = null, c_26_L = null;
      XSSFCell c_27_A = null, c_27_B = null, c_27_C = null, c_27_D = null, c_27_E = null, c_27_F = null, c_27_G = null, c_27_H = null, c_27_I = null, c_27_J = null, c_27_K = null, c_27_L = null;
      XSSFCell c_28_A = null, c_28_B = null, c_28_C = null, c_28_D = null, c_28_E = null, c_28_F = null, c_28_G = null, c_28_H = null, c_28_I = null, c_28_J = null, c_28_K = null, c_28_L = null;
      XSSFCell c_29_A = null, c_29_B = null, c_29_C = null, c_29_D = null, c_29_E = null, c_29_F = null, c_29_G = null, c_29_H = null, c_29_I = null, c_29_J = null, c_29_K = null, c_29_L = null;
      XSSFCell c_30_A = null, c_30_B = null, c_30_C = null, c_30_D = null, c_30_E = null, c_30_F = null, c_30_G = null, c_30_H = null, c_30_I = null, c_30_J = null, c_30_K = null, c_30_L = null;
      XSSFCell c_31_A = null, c_31_B = null, c_31_C = null, c_31_D = null, c_31_E = null, c_31_F = null, c_31_G = null, c_31_H = null, c_31_I = null, c_31_J = null, c_31_K = null, c_31_L = null;
      XSSFCell c_32_A = null, c_32_B = null, c_32_C = null, c_32_D = null, c_32_E = null, c_32_F = null, c_32_G = null, c_32_H = null, c_32_I = null, c_32_J = null, c_32_K = null, c_32_L = null;
      XSSFCell c_33_A = null, c_33_B = null, c_33_C = null, c_33_D = null, c_33_E = null, c_33_F = null, c_33_G = null, c_33_H = null, c_33_I = null, c_33_J = null, c_33_K = null, c_33_L = null;
      XSSFCell c_34_A = null, c_34_B = null, c_34_C = null, c_34_D = null, c_34_E = null, c_34_F = null, c_34_G = null, c_34_H = null, c_34_I = null, c_34_J = null, c_34_K = null, c_34_L = null;
      XSSFCell c_35_A = null, c_35_B = null, c_35_C = null, c_35_D = null, c_35_E = null, c_35_F = null, c_35_G = null, c_35_H = null, c_35_I = null, c_35_J = null, c_35_K = null, c_35_L = null;
      XSSFCell c_36_A = null, c_36_B = null, c_36_C = null, c_36_D = null, c_36_E = null, c_36_F = null, c_36_G = null, c_36_H = null, c_36_I = null, c_36_J = null, c_36_K = null, c_36_L = null;
      XSSFCell c_37_A = null, c_37_B = null, c_37_C = null, c_37_D = null, c_37_E = null, c_37_F = null, c_37_G = null, c_37_H = null, c_37_I = null, c_37_J = null, c_37_K = null, c_37_L = null;
      XSSFCell c_38_A = null, c_38_B = null, c_38_C = null, c_38_D = null, c_38_E = null, c_38_F = null, c_38_G = null, c_38_H = null, c_38_I = null, c_38_J = null, c_38_K = null, c_38_L = null;
      XSSFCell c_39_A = null, c_39_B = null, c_39_C = null, c_39_D = null, c_39_E = null, c_39_F = null, c_39_G = null, c_39_H = null, c_39_I = null, c_39_J = null, c_39_K = null, c_39_L = null;
      XSSFFont font1 = wb.createFont();
      XSSFCellStyle style1 = wb.createCellStyle();
      font1.setBold(true);
      font1.setFontName("");
      font1.setFontHeightInPoints((short)18);
      font1.setUnderline((byte)2);
      style1.setFont((Font)font1);
      style1.setBorderBottom(BorderStyle.THICK);
      style1.setBorderLeft(BorderStyle.THIN);
      style1.setBorderRight(BorderStyle.THIN);
      style1.setBorderTop(BorderStyle.THIN);
      style1.setAlignment(HorizontalAlignment.CENTER);
      style1.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font2 = wb.createFont();
      XSSFCellStyle style2 = wb.createCellStyle();
      font2.setBold(false);
      font2.setFontName("");
      font2.setFontHeightInPoints((short)12);
      style2.setFont((Font)font2);
      style2.setWrapText(true);
      style2.setBorderBottom(BorderStyle.THICK);
      style2.setBorderLeft(BorderStyle.NONE);
      style2.setBorderRight(BorderStyle.NONE);
      style2.setBorderTop(BorderStyle.THICK);
      style2.setAlignment(HorizontalAlignment.CENTER);
      style2.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font3 = wb.createFont();
      XSSFCellStyle style3 = wb.createCellStyle();
      font3.setBold(false);
      font3.setFontName("");
      font3.setFontHeightInPoints((short)12);
      style3.setFont((Font)font3);
      style3.setWrapText(true);
      style3.setBorderBottom(BorderStyle.NONE);
      style3.setBorderLeft(BorderStyle.NONE);
      style3.setBorderRight(BorderStyle.NONE);
      style3.setBorderTop(BorderStyle.NONE);
      style3.setAlignment(HorizontalAlignment.LEFT);
      style3.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font4 = wb.createFont();
      XSSFCellStyle style4 = wb.createCellStyle();
      font4.setBold(true);
      font4.setFontName("");
      font4.setFontHeightInPoints((short)11);
      style4.setFont((Font)font4);
      style4.setWrapText(true);
      style4.setBorderBottom(BorderStyle.THIN);
      style4.setBorderLeft(BorderStyle.THIN);
      style4.setBorderRight(BorderStyle.THIN);
      style4.setBorderTop(BorderStyle.THIN);
      style4.setAlignment(HorizontalAlignment.CENTER);
      style4.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font5 = wb.createFont();
      XSSFCellStyle style5 = wb.createCellStyle();
      font5.setBold(false);
      font5.setFontName("");
      font5.setFontHeightInPoints((short)11);
      style5.setFont((Font)font5);
      style5.setWrapText(true);
      style5.setBorderBottom(BorderStyle.THIN);
      style5.setBorderLeft(BorderStyle.THIN);
      style5.setBorderRight(BorderStyle.THIN);
      style5.setBorderTop(BorderStyle.THIN);
      style5.setAlignment(HorizontalAlignment.CENTER);
      style5.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font6 = wb.createFont();
      XSSFCellStyle style6 = wb.createCellStyle();
      font6.setBold(false);
      font6.setFontName("");
      font6.setFontHeightInPoints((short)11);
      style6.setFont((Font)font6);
      style6.setWrapText(true);
      style6.setBorderBottom(BorderStyle.THIN);
      style6.setBorderLeft(BorderStyle.THIN);
      style6.setBorderRight(BorderStyle.THIN);
      style6.setBorderTop(BorderStyle.THIN);
      style6.setAlignment(HorizontalAlignment.LEFT);
      style6.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font7 = wb.createFont();
      XSSFCellStyle style7 = wb.createCellStyle();
      font7.setBold(false);
      font7.setFontName("");
      font7.setFontHeightInPoints((short)11);
      style7.setFont((Font)font7);
      style7.setWrapText(true);
      style7.setBorderBottom(BorderStyle.THIN);
      style7.setBorderLeft(BorderStyle.THIN);
      style7.setBorderRight(BorderStyle.THIN);
      style7.setBorderTop(BorderStyle.THIN);
      style7.setAlignment(HorizontalAlignment.CENTER);
      style7.setVerticalAlignment(VerticalAlignment.CENTER);
      style7.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
      style7.setFillPattern(FillPatternType.SOLID_FOREGROUND);
      sheet = wb.getSheetAt(0);
      sheet.setColumnWidth(0, 3500);
      sheet.setColumnWidth(1, 4000);
      sheet.setColumnWidth(2, 5000);
      sheet.setColumnWidth(3, 2000);
      sheet.setColumnWidth(4, 3500);
      sheet.setColumnWidth(5, 3500);
      XSSFRow row = sheet.createRow(0);
      row.setHeight((short)600);
      c_01_A = row.createCell(0);
      c_01_A.setCellStyle((CellStyle)style3);
      c_01_A.setCellValue("");
      c_01_B = row.createCell(1);
      c_01_B.setCellStyle((CellStyle)style3);
      c_01_B.setCellValue("");
      c_01_C = row.createCell(2);
      c_01_C.setCellStyle((CellStyle)style3);
      c_01_C.setCellValue("");
      c_01_D = row.createCell(3);
      c_01_D.setCellStyle((CellStyle)style3);
      c_01_D.setCellValue("");
      c_01_E = row.createCell(4);
      c_01_E.setCellStyle((CellStyle)style3);
      c_01_E.setCellValue("");
      c_01_F = row.createCell(5);
      c_01_F.setCellStyle((CellStyle)style3);
      c_01_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 5));
      row = sheet.createRow(1);
      row.setHeight((short)800);
      c_01_A = row.createCell(0);
      c_01_A.setCellStyle((CellStyle)style1);
      c_01_A.setCellValue("");
      c_01_B = row.createCell(1);
      c_01_B.setCellStyle((CellStyle)style1);
      c_01_B.setCellValue("");
      c_01_C = row.createCell(2);
      c_01_C.setCellStyle((CellStyle)style1);
      c_01_C.setCellValue("");
      c_01_D = row.createCell(3);
      c_01_D.setCellStyle((CellStyle)style1);
      c_01_D.setCellValue("");
      c_01_E = row.createCell(4);
      c_01_E.setCellStyle((CellStyle)style1);
      c_01_E.setCellValue("");
      c_01_F = row.createCell(5);
      c_01_F.setCellStyle((CellStyle)style1);
      c_01_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(1, 1, 0, 5));
      row = sheet.createRow(2);
      row.setHeight((short)600);
      c_02_A = row.createCell(0);
      c_02_A.setCellStyle((CellStyle)style5);
      c_02_A.setCellValue("");
      c_02_B = row.createCell(1);
      c_02_B.setCellStyle((CellStyle)style5);
      c_02_B.setCellValue("");
      c_02_C = row.createCell(2);
      c_02_C.setCellStyle((CellStyle)style5);
      c_02_C.setCellValue(Util.nvl(devcInfo.get("tmpRaceAgency")));
      c_02_D = row.createCell(3);
      c_02_D.setCellStyle((CellStyle)style5);
      c_02_D.setCellValue("");
      c_02_E = row.createCell(4);
      c_02_E.setCellStyle((CellStyle)style5);
      c_02_E.setCellValue("");
      c_02_F = row.createCell(5);
      c_02_F.setCellStyle((CellStyle)style5);
      c_02_F.setCellValue(Util.nvl(devcInfo.get("tmpRaceNumber")));
      sheet.addMergedRegion(new CellRangeAddress(2, 2, 3, 4));
      row = sheet.createRow(3);
      row.setHeight((short)500);
      c_03_A = row.createCell(0);
      c_03_A.setCellStyle((CellStyle)style5);
      c_03_A.setCellValue("");
      c_03_B = row.createCell(1);
      c_03_B.setCellStyle((CellStyle)style5);
      c_03_B.setCellValue("");
      c_03_C = row.createCell(2);
      c_03_C.setCellStyle((CellStyle)style5);
      c_03_C.setCellValue(Util.nvl(devcInfo.get("modifyDateView")));
      c_03_D = row.createCell(3);
      c_03_D.setCellStyle((CellStyle)style5);
      c_03_D.setCellValue("");
      c_03_E = row.createCell(4);
      c_03_E.setCellStyle((CellStyle)style5);
      c_03_E.setCellValue("");
      c_03_F = row.createCell(5);
      c_03_F.setCellStyle((CellStyle)style5);
      c_03_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(3, 3, 2, 5));
      String drChangeYn = Util.nvl(devcInfo.get("drivingModeChangeYn")).equals("Y") ? "": "";
      String spChangeYn = Util.nvl(devcInfo.get("spdRangeChangeYn")).equals("Y") ? "": "";
      String dvChangeYn = Util.nvl(devcInfo.get("deviceChangeYn")).equals("Y") ? "": "";
      row = sheet.createRow(4);
      row.setHeight((short)500);
      c_04_A = row.createCell(0);
      c_04_A.setCellStyle((CellStyle)style5);
      c_04_A.setCellValue("");
      c_04_B = row.createCell(1);
      c_04_B.setCellStyle((CellStyle)style7);
      c_04_B.setCellValue("");
      c_04_C = row.createCell(2);
      c_04_C.setCellStyle((CellStyle)style7);
      c_04_C.setCellValue("");
      c_04_D = row.createCell(3);
      c_04_D.setCellStyle((CellStyle)style7);
      c_04_D.setCellValue("");
      c_04_E = row.createCell(4);
      c_04_E.setCellStyle((CellStyle)style7);
      c_04_E.setCellValue("");
      c_04_F = row.createCell(5);
      c_04_F.setCellStyle((CellStyle)style7);
      c_04_F.setCellValue("");
      row = sheet.createRow(5);
      row.setHeight((short)500);
      c_05_A = row.createCell(0);
      c_05_A.setCellStyle((CellStyle)style5);
      c_05_A.setCellValue("");
      c_05_B = row.createCell(1);
      c_05_B.setCellStyle((CellStyle)style7);
      c_05_B.setCellValue("");
      c_05_C = row.createCell(2);
      c_05_C.setCellStyle((CellStyle)style5);
      c_05_C.setCellValue("");
      c_05_D = row.createCell(3);
      c_05_D.setCellStyle((CellStyle)style5);
      c_05_D.setCellValue("");
      c_05_E = row.createCell(4);
      c_05_E.setCellStyle((CellStyle)style5);
      c_05_E.setCellValue("");
      c_05_F = row.createCell(5);
      c_05_F.setCellStyle((CellStyle)style5);
      c_05_F.setCellValue(drChangeYn);
      sheet.addMergedRegion(new CellRangeAddress(4, 5, 1, 1));
      sheet.addMergedRegion(new CellRangeAddress(4, 4, 2, 4));
      sheet.addMergedRegion(new CellRangeAddress(5, 5, 2, 4));
      row = sheet.createRow(6);
      row.setHeight((short)500);
      c_06_A = row.createCell(0);
      c_06_A.setCellStyle((CellStyle)style5);
      c_06_A.setCellValue("");
      c_06_B = row.createCell(1);
      c_06_B.setCellStyle((CellStyle)style7);
      c_06_B.setCellValue("");
      c_06_C = row.createCell(2);
      c_06_C.setCellStyle((CellStyle)style7);
      c_06_C.setCellValue("");
      c_06_D = row.createCell(3);
      c_06_D.setCellStyle((CellStyle)style7);
      c_06_D.setCellValue("");
      c_06_E = row.createCell(4);
      c_06_E.setCellStyle((CellStyle)style7);
      c_06_E.setCellValue("");
      c_06_F = row.createCell(5);
      c_06_F.setCellStyle((CellStyle)style7);
      c_06_F.setCellValue("");
      row = sheet.createRow(7);
      row.setHeight((short)1400);
      c_07_A = row.createCell(0);
      c_07_A.setCellStyle((CellStyle)style5);
      c_07_A.setCellValue("");
      c_07_B = row.createCell(1);
      c_07_B.setCellStyle((CellStyle)style5);
      c_07_B.setCellValue("");
      c_07_C = row.createCell(2);
      c_07_C.setCellStyle((CellStyle)style6);
      c_07_C.setCellValue(Util.nvl(devcInfo.get("dmBeforeSpec")));
      c_07_D = row.createCell(3);
      c_07_D.setCellStyle((CellStyle)style6);
      c_07_D.setCellValue("");
      c_07_E = row.createCell(4);
      c_07_E.setCellStyle((CellStyle)style6);
      c_07_E.setCellValue(Util.nvl(devcInfo.get("dmAfterSpec")));
      c_07_F = row.createCell(5);
      c_07_F.setCellStyle((CellStyle)style6);
      c_07_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(6, 7, 1, 1));
      sheet.addMergedRegion(new CellRangeAddress(6, 6, 2, 3));
      sheet.addMergedRegion(new CellRangeAddress(6, 6, 4, 5));
      sheet.addMergedRegion(new CellRangeAddress(7, 7, 2, 3));
      sheet.addMergedRegion(new CellRangeAddress(7, 7, 4, 5));
      row = sheet.createRow(8);
      row.setHeight((short)500);
      c_08_A = row.createCell(0);
      c_08_A.setCellStyle((CellStyle)style5);
      c_08_A.setCellValue("");
      c_08_B = row.createCell(1);
      c_08_B.setCellStyle((CellStyle)style7);
      c_08_B.setCellValue("");
      c_08_C = row.createCell(2);
      c_08_C.setCellStyle((CellStyle)style7);
      c_08_C.setCellValue("");
      c_08_D = row.createCell(3);
      c_08_D.setCellStyle((CellStyle)style7);
      c_08_D.setCellValue("");
      c_08_E = row.createCell(4);
      c_08_E.setCellStyle((CellStyle)style7);
      c_08_E.setCellValue("");
      c_08_F = row.createCell(5);
      c_08_F.setCellStyle((CellStyle)style7);
      c_08_F.setCellValue("");
      row = sheet.createRow(9);
      row.setHeight((short)500);
      c_09_A = row.createCell(0);
      c_09_A.setCellStyle((CellStyle)style5);
      c_09_A.setCellValue("");
      c_09_B = row.createCell(1);
      c_09_B.setCellStyle((CellStyle)style7);
      c_09_B.setCellValue("");
      c_09_C = row.createCell(2);
      c_09_C.setCellStyle((CellStyle)style5);
      c_09_C.setCellValue("");
      c_09_D = row.createCell(3);
      c_09_D.setCellStyle((CellStyle)style5);
      c_09_D.setCellValue("");
      c_09_E = row.createCell(4);
      c_09_E.setCellStyle((CellStyle)style5);
      c_09_E.setCellValue("");
      c_09_F = row.createCell(5);
      c_09_F.setCellStyle((CellStyle)style5);
      c_09_F.setCellValue(spChangeYn);
      sheet.addMergedRegion(new CellRangeAddress(8, 9, 1, 1));
      sheet.addMergedRegion(new CellRangeAddress(8, 8, 2, 4));
      sheet.addMergedRegion(new CellRangeAddress(9, 9, 2, 4));
      row = sheet.createRow(10);
      row.setHeight((short)500);
      c_10_A = row.createCell(0);
      c_10_A.setCellStyle((CellStyle)style5);
      c_10_A.setCellValue("");
      c_10_B = row.createCell(1);
      c_10_B.setCellStyle((CellStyle)style7);
      c_10_B.setCellValue("");
      c_10_C = row.createCell(2);
      c_10_C.setCellStyle((CellStyle)style7);
      c_10_C.setCellValue("");
      c_10_D = row.createCell(3);
      c_10_D.setCellStyle((CellStyle)style7);
      c_10_D.setCellValue("");
      c_10_E = row.createCell(4);
      c_10_E.setCellStyle((CellStyle)style7);
      c_10_E.setCellValue("");
      c_10_F = row.createCell(5);
      c_10_F.setCellStyle((CellStyle)style7);
      c_10_F.setCellValue("");
      row = sheet.createRow(11);
      row.setHeight((short)1400);
      c_11_A = row.createCell(0);
      c_11_A.setCellStyle((CellStyle)style5);
      c_11_A.setCellValue("");
      c_11_B = row.createCell(1);
      c_11_B.setCellStyle((CellStyle)style5);
      c_11_B.setCellValue("");
      c_11_C = row.createCell(2);
      c_11_C.setCellStyle((CellStyle)style6);
      c_11_C.setCellValue(Util.nvl(devcInfo.get("srcBeforeSpec")));
      c_11_D = row.createCell(3);
      c_11_D.setCellStyle((CellStyle)style6);
      c_11_D.setCellValue("");
      c_11_E = row.createCell(4);
      c_11_E.setCellStyle((CellStyle)style6);
      c_11_E.setCellValue(Util.nvl(devcInfo.get("srcAfterSpec")));
      c_11_F = row.createCell(5);
      c_11_F.setCellStyle((CellStyle)style6);
      c_11_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(10, 11, 1, 1));
      sheet.addMergedRegion(new CellRangeAddress(10, 10, 2, 3));
      sheet.addMergedRegion(new CellRangeAddress(10, 10, 4, 5));
      sheet.addMergedRegion(new CellRangeAddress(11, 11, 2, 3));
      sheet.addMergedRegion(new CellRangeAddress(11, 11, 4, 5));
      row = sheet.createRow(12);
      row.setHeight((short)500);
      c_12_A = row.createCell(0);
      c_12_A.setCellStyle((CellStyle)style5);
      c_12_A.setCellValue("");
      c_12_B = row.createCell(1);
      c_12_B.setCellStyle((CellStyle)style7);
      c_12_B.setCellValue("");
      c_12_C = row.createCell(2);
      c_12_C.setCellStyle((CellStyle)style7);
      c_12_C.setCellValue("");
      c_12_D = row.createCell(3);
      c_12_D.setCellStyle((CellStyle)style7);
      c_12_D.setCellValue("");
      c_12_E = row.createCell(4);
      c_12_E.setCellStyle((CellStyle)style7);
      c_12_E.setCellValue("");
      c_12_F = row.createCell(5);
      c_12_F.setCellStyle((CellStyle)style7);
      c_12_F.setCellValue("");
      row = sheet.createRow(13);
      row.setHeight((short)500);
      c_13_A = row.createCell(0);
      c_13_A.setCellStyle((CellStyle)style5);
      c_13_A.setCellValue("");
      c_13_B = row.createCell(1);
      c_13_B.setCellStyle((CellStyle)style7);
      c_13_B.setCellValue("");
      c_13_C = row.createCell(2);
      c_13_C.setCellStyle((CellStyle)style5);
      c_13_C.setCellValue("");
      c_13_D = row.createCell(3);
      c_13_D.setCellStyle((CellStyle)style5);
      c_13_D.setCellValue("");
      c_13_E = row.createCell(4);
      c_13_E.setCellStyle((CellStyle)style5);
      c_13_E.setCellValue("");
      c_13_F = row.createCell(5);
      c_13_F.setCellStyle((CellStyle)style5);
      c_13_F.setCellValue(dvChangeYn);
      sheet.addMergedRegion(new CellRangeAddress(12, 13, 1, 1));
      sheet.addMergedRegion(new CellRangeAddress(12, 12, 2, 4));
      sheet.addMergedRegion(new CellRangeAddress(13, 13, 2, 4));
      row = sheet.createRow(14);
      row.setHeight((short)800);
      c_14_A = row.createCell(0);
      c_14_A.setCellStyle((CellStyle)style5);
      c_14_A.setCellValue("");
      c_14_B = row.createCell(1);
      c_14_B.setCellStyle((CellStyle)style7);
      c_14_B.setCellValue("");
      c_14_C = row.createCell(2);
      c_14_C.setCellStyle((CellStyle)style7);
      c_14_C.setCellValue("");
      c_14_D = row.createCell(3);
      c_14_D.setCellStyle((CellStyle)style7);
      c_14_D.setCellValue("");
      c_14_E = row.createCell(4);
      c_14_E.setCellStyle((CellStyle)style7);
      c_14_E.setCellValue("");
      c_14_F = row.createCell(5);
      c_14_F.setCellStyle((CellStyle)style7);
      c_14_F.setCellValue("");
      row = sheet.createRow(15);
      row.setHeight((short)1400);
      c_15_A = row.createCell(0);
      c_15_A.setCellStyle((CellStyle)style5);
      c_15_A.setCellValue("");
      c_15_B = row.createCell(1);
      c_15_B.setCellStyle((CellStyle)style5);
      c_15_B.setCellValue("");
      c_15_C = row.createCell(2);
      c_15_C.setCellStyle((CellStyle)style6);
      c_15_C.setCellValue(Util.nvl(devcInfo.get("dcBeforeSpec")));
      c_15_D = row.createCell(3);
      c_15_D.setCellStyle((CellStyle)style6);
      c_15_D.setCellValue("");
      c_15_E = row.createCell(4);
      c_15_E.setCellStyle((CellStyle)style6);
      c_15_E.setCellValue(Util.nvl(devcInfo.get("dcAfterSpec")));
      c_15_F = row.createCell(5);
      c_15_F.setCellStyle((CellStyle)style6);
      c_15_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(14, 15, 1, 1));
      sheet.addMergedRegion(new CellRangeAddress(14, 14, 2, 3));
      sheet.addMergedRegion(new CellRangeAddress(14, 14, 4, 5));
      sheet.addMergedRegion(new CellRangeAddress(15, 15, 2, 3));
      sheet.addMergedRegion(new CellRangeAddress(15, 15, 4, 5));
      row = sheet.createRow(16);
      row.setHeight((short)1800);
      c_16_A = row.createCell(0);
      c_16_A.setCellStyle((CellStyle)style5);
      c_16_A.setCellValue("");
      c_16_B = row.createCell(1);
      c_16_B.setCellStyle((CellStyle)style7);
      c_16_B.setCellValue("");
      c_16_C = row.createCell(2);
      c_16_C.setCellStyle((CellStyle)style6);
      c_16_C.setCellValue(Util.nvl(devcInfo.get("changeInfo")));
      c_16_D = row.createCell(3);
      c_16_D.setCellStyle((CellStyle)style6);
      c_16_D.setCellValue("");
      c_16_E = row.createCell(4);
      c_16_E.setCellStyle((CellStyle)style6);
      c_16_E.setCellValue("");
      c_16_F = row.createCell(5);
      c_16_F.setCellStyle((CellStyle)style6);
      c_16_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(3, 16, 0, 0));
      sheet.addMergedRegion(new CellRangeAddress(16, 16, 2, 5));
      row = sheet.createRow(17);
      row.setHeight((short)2500);
      c_01_A = row.createCell(0);
      c_01_A.setCellStyle((CellStyle)style2);
      c_01_A.setCellValue("");
      c_01_B = row.createCell(1);
      c_01_B.setCellStyle((CellStyle)style2);
      c_01_B.setCellValue("");
      c_01_C = row.createCell(2);
      c_01_C.setCellStyle((CellStyle)style2);
      c_01_C.setCellValue("");
      c_01_D = row.createCell(3);
      c_01_D.setCellStyle((CellStyle)style2);
      c_01_D.setCellValue("");
      c_01_E = row.createCell(4);
      c_01_E.setCellStyle((CellStyle)style2);
      c_01_E.setCellValue("");
      c_01_F = row.createCell(5);
      c_01_F.setCellStyle((CellStyle)style2);
      c_01_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(17, 17, 0, 5));
      FileOutputStream fileOutput = null;
      try {
        if (filePath == null || !"".equals(filePath));
        fileOutput = new FileOutputStream(filePath);
        wb.write(fileOutput);
      } catch (IOException iOException1) {
        IOException ioe = null;
        log.info("[DevcExcel Exception] 1: " + ioe.toString());
        result = "0";
      } finally {
        if (fileOutput != null)
          try {
            fileOutput.close();
          } catch (IOException iOException1) {
            IOException e1 = null;
            log.info("[DevcExcel fileOutput] : " + e1.toString());
          }  
      } 
    } catch (Exception e) {
      log.info("[DevcExcel Exception] 2: " + e.toString());
      result = "0";
    } 
    return result;
  }
}
