package nzero.admin.record.excel;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import nzero.admin.egovframework.cmmn.util.Util;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class IncdExcel {
  private static Log log = LogFactory.getLog(IncdExcel.class);
  
  public static String incdExcelMake(String filePath, String filenm, Map<String, String> incdInfo, List<?> carList) {
    String result = "1";
    try {
      XSSFWorkbook wb = new XSSFWorkbook();
      XSSFSheet sheet = wb.createSheet(String.valueOf(incdInfo.get("tmpRaceNumber")));
      XSSFCell c_01_A = null, c_01_B = null, c_01_C = null, c_01_D = null, c_01_E = null, c_01_F = null, c_01_G = null, c_01_H = null, c_01_I = null, c_01_J = null, c_01_K = null, c_01_L = null;
      XSSFCell c_02_A = null, c_02_B = null, c_02_C = null, c_02_D = null, c_02_E = null, c_02_F = null, c_02_G = null, c_02_H = null, c_02_I = null, c_02_J = null, c_02_K = null, c_02_L = null;
      XSSFCell c_03_A = null, c_03_B = null, c_03_C = null, c_03_D = null, c_03_E = null, c_03_F = null, c_03_G = null, c_03_H = null, c_03_I = null, c_03_J = null, c_03_K = null, c_03_L = null;
      XSSFCell c_04_A = null, c_04_B = null, c_04_C = null, c_04_D = null, c_04_E = null, c_04_F = null, c_04_G = null, c_04_H = null, c_04_I = null, c_04_J = null, c_04_K = null, c_04_L = null;
      XSSFCell c_05_A = null, c_05_B = null, c_05_C = null, c_05_D = null, c_05_E = null, c_05_F = null, c_05_G = null, c_05_H = null, c_05_I = null, c_05_J = null, c_05_K = null, c_05_L = null;
      XSSFCell c_06_A = null, c_06_B = null, c_06_C = null, c_06_D = null, c_06_E = null, c_06_F = null, c_06_G = null, c_06_H = null, c_06_I = null, c_06_J = null, c_06_K = null, c_06_L = null;
      XSSFCell c_07_A = null, c_07_B = null, c_07_C = null, c_07_D = null, c_07_E = null, c_07_F = null, c_07_G = null, c_07_H = null, c_07_I = null, c_07_J = null, c_07_K = null, c_07_L = null;
      XSSFCell c_08_A = null, c_08_B = null, c_08_C = null, c_08_D = null, c_08_E = null, c_08_F = null, c_08_G = null, c_08_H = null, c_08_I = null, c_08_J = null, c_08_K = null, c_08_L = null;
      XSSFCell c_09_A = null, c_09_B = null, c_09_C = null, c_09_D = null, c_09_E = null, c_09_F = null, c_09_G = null, c_09_H = null, c_09_I = null, c_09_J = null, c_09_K = null, c_09_L = null;
      XSSFCell c_10_A = null, c_10_B = null, c_10_C = null, c_10_D = null, c_10_E = null, c_10_F = null, c_10_G = null, c_10_H = null, c_10_I = null, c_10_J = null, c_10_K = null, c_10_L = null;
      XSSFCell c_11_A = null, c_11_B = null, c_11_C = null, c_11_D = null, c_11_E = null, c_11_F = null, c_11_G = null, c_11_H = null, c_11_I = null, c_11_J = null, c_11_K = null, c_11_L = null;
      XSSFCell c_12_A = null, c_12_B = null, c_12_C = null, c_12_D = null, c_12_E = null, c_12_F = null, c_12_G = null, c_12_H = null, c_12_I = null, c_12_J = null, c_12_K = null, c_12_L = null;
      XSSFCell c_13_A = null, c_13_B = null, c_13_C = null, c_13_D = null, c_13_E = null, c_13_F = null, c_13_G = null, c_13_H = null, c_13_I = null, c_13_J = null, c_13_K = null, c_13_L = null;
      XSSFCell c_14_A = null, c_14_B = null, c_14_C = null, c_14_D = null, c_14_E = null, c_14_F = null, c_14_G = null, c_14_H = null, c_14_I = null, c_14_J = null, c_14_K = null, c_14_L = null;
      XSSFCell c_15_A = null, c_15_B = null, c_15_C = null, c_15_D = null, c_15_E = null, c_15_F = null, c_15_G = null, c_15_H = null, c_15_I = null, c_15_J = null, c_15_K = null, c_15_L = null;
      XSSFCell c_16_A = null, c_16_B = null, c_16_C = null, c_16_D = null, c_16_E = null, c_16_F = null, c_16_G = null, c_16_H = null, c_16_I = null, c_16_J = null, c_16_K = null, c_16_L = null;
      XSSFCell c_17_A = null, c_17_B = null, c_17_C = null, c_17_D = null, c_17_E = null, c_17_F = null, c_17_G = null, c_17_H = null, c_17_I = null, c_17_J = null, c_17_K = null, c_17_L = null;
      XSSFCell c_18_A = null, c_18_B = null, c_18_C = null, c_18_D = null, c_18_E = null, c_18_F = null, c_18_G = null, c_18_H = null, c_18_I = null, c_18_J = null, c_18_K = null, c_18_L = null;
      XSSFCell c_19_A = null, c_19_B = null, c_19_C = null, c_19_D = null, c_19_E = null, c_19_F = null, c_19_G = null, c_19_H = null, c_19_I = null, c_19_J = null, c_19_K = null, c_19_L = null;
      XSSFCell c_20_A = null, c_20_B = null, c_20_C = null, c_20_D = null, c_20_E = null, c_20_F = null, c_20_G = null, c_20_H = null, c_20_I = null, c_20_J = null, c_20_K = null, c_20_L = null;
      XSSFCell c_21_A = null, c_21_B = null, c_21_C = null, c_21_D = null, c_21_E = null, c_21_F = null, c_21_G = null, c_21_H = null, c_21_I = null, c_21_J = null, c_21_K = null, c_21_L = null;
      XSSFCell c_22_A = null, c_22_B = null, c_22_C = null, c_22_D = null, c_22_E = null, c_22_F = null, c_22_G = null, c_22_H = null, c_22_I = null, c_22_J = null, c_22_K = null, c_22_L = null;
      XSSFCell c_23_A = null, c_23_B = null, c_23_C = null, c_23_D = null, c_23_E = null, c_23_F = null, c_23_G = null, c_23_H = null, c_23_I = null, c_23_J = null, c_23_K = null, c_23_L = null;
      XSSFCell c_24_A = null, c_24_B = null, c_24_C = null, c_24_D = null, c_24_E = null, c_24_F = null, c_24_G = null, c_24_H = null, c_24_I = null, c_24_J = null, c_24_K = null, c_24_L = null;
      XSSFCell c_25_A = null, c_25_B = null, c_25_C = null, c_25_D = null, c_25_E = null, c_25_F = null, c_25_G = null, c_25_H = null, c_25_I = null, c_25_J = null, c_25_K = null, c_25_L = null;
      XSSFCell c_26_A = null, c_26_B = null, c_26_C = null, c_26_D = null, c_26_E = null, c_26_F = null, c_26_G = null, c_26_H = null, c_26_I = null, c_26_J = null, c_26_K = null, c_26_L = null;
      XSSFCell c_27_A = null, c_27_B = null, c_27_C = null, c_27_D = null, c_27_E = null, c_27_F = null, c_27_G = null, c_27_H = null, c_27_I = null, c_27_J = null, c_27_K = null, c_27_L = null;
      XSSFCell c_28_A = null, c_28_B = null, c_28_C = null, c_28_D = null, c_28_E = null, c_28_F = null, c_28_G = null, c_28_H = null, c_28_I = null, c_28_J = null, c_28_K = null, c_28_L = null;
      XSSFCell c_29_A = null, c_29_B = null, c_29_C = null, c_29_D = null, c_29_E = null, c_29_F = null, c_29_G = null, c_29_H = null, c_29_I = null, c_29_J = null, c_29_K = null, c_29_L = null;
      XSSFCell c_30_A = null, c_30_B = null, c_30_C = null, c_30_D = null, c_30_E = null, c_30_F = null, c_30_G = null, c_30_H = null, c_30_I = null, c_30_J = null, c_30_K = null, c_30_L = null;
      XSSFCell c_31_A = null, c_31_B = null, c_31_C = null, c_31_D = null, c_31_E = null, c_31_F = null, c_31_G = null, c_31_H = null, c_31_I = null, c_31_J = null, c_31_K = null, c_31_L = null;
      XSSFCell c_32_A = null, c_32_B = null, c_32_C = null, c_32_D = null, c_32_E = null, c_32_F = null, c_32_G = null, c_32_H = null, c_32_I = null, c_32_J = null, c_32_K = null, c_32_L = null;
      XSSFCell c_33_A = null, c_33_B = null, c_33_C = null, c_33_D = null, c_33_E = null, c_33_F = null, c_33_G = null, c_33_H = null, c_33_I = null, c_33_J = null, c_33_K = null, c_33_L = null;
      XSSFCell c_34_A = null, c_34_B = null, c_34_C = null, c_34_D = null, c_34_E = null, c_34_F = null, c_34_G = null, c_34_H = null, c_34_I = null, c_34_J = null, c_34_K = null, c_34_L = null;
      XSSFCell c_35_A = null, c_35_B = null, c_35_C = null, c_35_D = null, c_35_E = null, c_35_F = null, c_35_G = null, c_35_H = null, c_35_I = null, c_35_J = null, c_35_K = null, c_35_L = null;
      XSSFCell c_36_A = null, c_36_B = null, c_36_C = null, c_36_D = null, c_36_E = null, c_36_F = null, c_36_G = null, c_36_H = null, c_36_I = null, c_36_J = null, c_36_K = null, c_36_L = null;
      XSSFCell c_37_A = null, c_37_B = null, c_37_C = null, c_37_D = null, c_37_E = null, c_37_F = null, c_37_G = null, c_37_H = null, c_37_I = null, c_37_J = null, c_37_K = null, c_37_L = null;
      XSSFCell c_38_A = null, c_38_B = null, c_38_C = null, c_38_D = null, c_38_E = null, c_38_F = null, c_38_G = null, c_38_H = null, c_38_I = null, c_38_J = null, c_38_K = null, c_38_L = null;
      XSSFCell c_39_A = null, c_39_B = null, c_39_C = null, c_39_D = null, c_39_E = null, c_39_F = null, c_39_G = null, c_39_H = null, c_39_I = null, c_39_J = null, c_39_K = null, c_39_L = null;
      XSSFFont font1 = wb.createFont();
      XSSFCellStyle style1 = wb.createCellStyle();
      font1.setBold(true);
      font1.setFontName("");
      font1.setFontHeightInPoints((short)18);
      font1.setUnderline((byte)2);
      style1.setFont((Font)font1);
      style1.setBorderBottom(BorderStyle.THICK);
      style1.setBorderLeft(BorderStyle.THIN);
      style1.setBorderRight(BorderStyle.THIN);
      style1.setBorderTop(BorderStyle.THIN);
      style1.setAlignment(HorizontalAlignment.CENTER);
      style1.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font2 = wb.createFont();
      XSSFCellStyle style2 = wb.createCellStyle();
      font2.setBold(false);
      font2.setFontName("");
      font2.setFontHeightInPoints((short)12);
      style2.setFont((Font)font2);
      style2.setWrapText(true);
      style2.setBorderBottom(BorderStyle.THICK);
      style2.setBorderLeft(BorderStyle.NONE);
      style2.setBorderRight(BorderStyle.NONE);
      style2.setBorderTop(BorderStyle.THICK);
      style2.setAlignment(HorizontalAlignment.CENTER);
      style2.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font3 = wb.createFont();
      XSSFCellStyle style3 = wb.createCellStyle();
      font3.setBold(false);
      font3.setFontName("");
      font3.setFontHeightInPoints((short)12);
      style3.setFont((Font)font3);
      style3.setWrapText(true);
      style3.setBorderBottom(BorderStyle.NONE);
      style3.setBorderLeft(BorderStyle.NONE);
      style3.setBorderRight(BorderStyle.NONE);
      style3.setBorderTop(BorderStyle.NONE);
      style3.setAlignment(HorizontalAlignment.LEFT);
      style3.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font4 = wb.createFont();
      XSSFCellStyle style4 = wb.createCellStyle();
      font4.setBold(true);
      font4.setFontName("");
      font4.setFontHeightInPoints((short)11);
      style4.setFont((Font)font4);
      style4.setWrapText(true);
      style4.setBorderBottom(BorderStyle.THIN);
      style4.setBorderLeft(BorderStyle.THIN);
      style4.setBorderRight(BorderStyle.THIN);
      style4.setBorderTop(BorderStyle.THIN);
      style4.setAlignment(HorizontalAlignment.CENTER);
      style4.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font5 = wb.createFont();
      XSSFCellStyle style5 = wb.createCellStyle();
      font5.setBold(false);
      font5.setFontName("");
      font5.setFontHeightInPoints((short)11);
      style5.setFont((Font)font5);
      style5.setWrapText(true);
      style5.setBorderBottom(BorderStyle.THIN);
      style5.setBorderLeft(BorderStyle.THIN);
      style5.setBorderRight(BorderStyle.THIN);
      style5.setBorderTop(BorderStyle.THIN);
      style5.setAlignment(HorizontalAlignment.CENTER);
      style5.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font6 = wb.createFont();
      XSSFCellStyle style6 = wb.createCellStyle();
      font6.setBold(false);
      font6.setFontName("");
      font6.setFontHeightInPoints((short)11);
      style6.setFont((Font)font6);
      style6.setWrapText(true);
      style6.setBorderBottom(BorderStyle.THIN);
      style6.setBorderLeft(BorderStyle.THIN);
      style6.setBorderRight(BorderStyle.THIN);
      style6.setBorderTop(BorderStyle.THIN);
      style6.setAlignment(HorizontalAlignment.LEFT);
      style6.setVerticalAlignment(VerticalAlignment.CENTER);
      XSSFFont font7 = wb.createFont();
      XSSFCellStyle style7 = wb.createCellStyle();
      font7.setBold(false);
      font7.setFontName("");
      font7.setFontHeightInPoints((short)11);
      style7.setFont((Font)font7);
      style7.setWrapText(true);
      style7.setBorderBottom(BorderStyle.THIN);
      style7.setBorderLeft(BorderStyle.THIN);
      style7.setBorderRight(BorderStyle.THIN);
      style7.setBorderTop(BorderStyle.THIN);
      style7.setAlignment(HorizontalAlignment.CENTER);
      style7.setVerticalAlignment(VerticalAlignment.CENTER);
      style7.setFillForegroundColor(IndexedColors.GREY_80_PERCENT.getIndex());
      style7.setFillPattern(FillPatternType.SOLID_FOREGROUND);
      log.debug(" @@@@@@@@@@@@@@ : 1");
      sheet = wb.getSheetAt(0);
      sheet.setColumnWidth(0, 3000);
      sheet.setColumnWidth(1, 4000);
      sheet.setColumnWidth(2, 5000);
      sheet.setColumnWidth(3, 2500);
      sheet.setColumnWidth(4, 2500);
      sheet.setColumnWidth(5, 4000);
      XSSFRow row = sheet.createRow(0);
      row.setHeight((short)600);
      c_01_A = row.createCell(0);
      c_01_A.setCellStyle((CellStyle)style3);
      c_01_A.setCellValue("");
      c_01_B = row.createCell(1);
      c_01_B.setCellStyle((CellStyle)style3);
      c_01_B.setCellValue("");
      c_01_C = row.createCell(2);
      c_01_C.setCellStyle((CellStyle)style3);
      c_01_C.setCellValue("");
      c_01_D = row.createCell(3);
      c_01_D.setCellStyle((CellStyle)style3);
      c_01_D.setCellValue("");
      c_01_E = row.createCell(4);
      c_01_E.setCellStyle((CellStyle)style3);
      c_01_E.setCellValue("");
      c_01_F = row.createCell(5);
      c_01_F.setCellStyle((CellStyle)style3);
      c_01_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 5));
      row = sheet.createRow(1);
      row.setHeight((short)800);
      c_01_A = row.createCell(0);
      c_01_A.setCellStyle((CellStyle)style1);
      c_01_A.setCellValue("");
      c_01_B = row.createCell(1);
      c_01_B.setCellStyle((CellStyle)style1);
      c_01_B.setCellValue("");
      c_01_C = row.createCell(2);
      c_01_C.setCellStyle((CellStyle)style1);
      c_01_C.setCellValue("");
      c_01_D = row.createCell(3);
      c_01_D.setCellStyle((CellStyle)style1);
      c_01_D.setCellValue("");
      c_01_E = row.createCell(4);
      c_01_E.setCellStyle((CellStyle)style1);
      c_01_E.setCellValue("");
      c_01_F = row.createCell(5);
      c_01_F.setCellStyle((CellStyle)style1);
      c_01_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(1, 1, 0, 5));
      row = sheet.createRow(2);
      row.setHeight((short)500);
      c_02_A = row.createCell(0);
      c_02_A.setCellStyle((CellStyle)style5);
      c_02_A.setCellValue("");
      c_02_B = row.createCell(1);
      c_02_B.setCellStyle((CellStyle)style5);
      c_02_B.setCellValue("");
      c_02_C = row.createCell(2);
      c_02_C.setCellStyle((CellStyle)style5);
      c_02_C.setCellValue(Util.nvl(incdInfo.get("tmpRaceAgency")));
      c_02_D = row.createCell(3);
      c_02_D.setCellStyle((CellStyle)style5);
      c_02_D.setCellValue("");
      c_02_E = row.createCell(4);
      c_02_E.setCellStyle((CellStyle)style5);
      c_02_E.setCellValue("");
      c_02_F = row.createCell(5);
      c_02_F.setCellStyle((CellStyle)style5);
      c_02_F.setCellValue(Util.nvl(incdInfo.get("tmpRaceNumber")));
      sheet.addMergedRegion(new CellRangeAddress(2, 2, 3, 4));
      log.debug(" @@@@@@@@@@@@@@ : 1-1");
      row = sheet.createRow(3);
      row.setHeight((short)500);
      c_03_A = row.createCell(0);
      c_03_A.setCellStyle((CellStyle)style5);
      c_03_A.setCellValue("");
      c_03_B = row.createCell(1);
      c_03_B.setCellStyle((CellStyle)style5);
      c_03_B.setCellValue("");
      c_03_C = row.createCell(2);
      c_03_C.setCellStyle((CellStyle)style6);
      c_03_C.setCellValue(Util.nvl(incdInfo.get("accDateView")));
      c_03_D = row.createCell(3);
      c_03_D.setCellStyle((CellStyle)style6);
      c_03_D.setCellValue("");
      c_03_E = row.createCell(4);
      c_03_E.setCellStyle((CellStyle)style6);
      c_03_E.setCellValue("");
      c_03_F = row.createCell(5);
      c_03_F.setCellStyle((CellStyle)style6);
      c_03_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(3, 3, 2, 5));
      log.debug(" @@@@@@@@@@@@@@ : 1-2");
      row = sheet.createRow(4);
      row.setHeight((short)500);
      c_04_A = row.createCell(0);
      c_04_A.setCellStyle((CellStyle)style5);
      c_04_A.setCellValue("");
      c_04_B = row.createCell(1);
      c_04_B.setCellStyle((CellStyle)style5);
      c_04_B.setCellValue("");
      c_04_C = row.createCell(2);
      c_04_C.setCellStyle((CellStyle)style6);
      c_04_C.setCellValue(Util.nvl(incdInfo.get("place")));
      c_04_D = row.createCell(3);
      c_04_D.setCellStyle((CellStyle)style6);
      c_04_D.setCellValue("");
      c_04_E = row.createCell(4);
      c_04_E.setCellStyle((CellStyle)style6);
      c_04_E.setCellValue("");
      c_04_F = row.createCell(5);
      c_04_F.setCellStyle((CellStyle)style6);
      c_04_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(4, 4, 2, 5));
      row = sheet.createRow(5);
      log.debug(" @@@@@@@@@@@@@@ : 1-3");
      row.setHeight((short)500);
      c_05_A = row.createCell(0);
      c_05_A.setCellStyle((CellStyle)style5);
      c_05_A.setCellValue("");
      c_05_B = row.createCell(1);
      c_05_B.setCellStyle((CellStyle)style5);
      c_05_B.setCellValue("");
      c_05_C = row.createCell(2);
      c_05_C.setCellStyle((CellStyle)style6);
      c_05_C.setCellValue(Util.nvl(incdInfo.get("weatherView")));
      c_05_D = row.createCell(3);
      c_05_D.setCellStyle((CellStyle)style6);
      c_05_D.setCellValue("");
      c_05_E = row.createCell(4);
      c_05_E.setCellStyle((CellStyle)style6);
      c_05_E.setCellValue("");
      c_05_F = row.createCell(5);
      c_05_F.setCellStyle((CellStyle)style6);
      c_05_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(5, 5, 2, 5));
      log.debug(" @@@@@@@@@@@@@@ : 2");
      row = sheet.createRow(6);
      row.setHeight((short)500);
      c_06_A = row.createCell(0);
      c_06_A.setCellStyle((CellStyle)style5);
      c_06_A.setCellValue("");
      c_06_B = row.createCell(1);
      c_06_B.setCellStyle((CellStyle)style5);
      c_06_B.setCellValue("");
      c_06_C = row.createCell(2);
      c_06_C.setCellStyle((CellStyle)style6);
      c_06_C.setCellValue(Util.nvl(incdInfo.get("roadSituationView")));
      c_06_D = row.createCell(3);
      c_06_D.setCellStyle((CellStyle)style6);
      c_06_D.setCellValue("");
      c_06_E = row.createCell(4);
      c_06_E.setCellStyle((CellStyle)style6);
      c_06_E.setCellValue("");
      c_06_F = row.createCell(5);
      c_06_F.setCellStyle((CellStyle)style6);
      c_06_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(3, 6, 0, 0));
      sheet.addMergedRegion(new CellRangeAddress(6, 6, 2, 5));
      log.debug(" @@@@@@@@@@@@@@ : 3");
      row = sheet.createRow(7);
      row.setHeight((short)500);
      c_07_A = row.createCell(0);
      c_07_A.setCellStyle((CellStyle)style5);
      c_07_A.setCellValue("");
      c_07_B = row.createCell(1);
      c_07_B.setCellStyle((CellStyle)style5);
      c_07_B.setCellValue("");
      c_07_C = row.createCell(2);
      c_07_C.setCellStyle((CellStyle)style6);
      c_07_C.setCellValue(Util.nvl(incdInfo.get("autocarDrivingModeView")));
      c_07_D = row.createCell(3);
      c_07_D.setCellStyle((CellStyle)style6);
      c_07_D.setCellValue("");
      c_07_E = row.createCell(4);
      c_07_E.setCellStyle((CellStyle)style6);
      c_07_E.setCellValue("");
      c_07_F = row.createCell(5);
      c_07_F.setCellStyle((CellStyle)style6);
      c_07_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(7, 7, 2, 5));
      String drStatus = Util.nvl(incdInfo.get("autocarDrivingStatusCd"));
      String drStatusView = "";
      if (drStatus.equals("101")) {
        drStatusView = Util.nvl(incdInfo.get("autocarDrivingStatusCdView")) + "(" + String.valueOf(incdInfo.get("autocarSpeed")) + " km/h)";
      } else if (drStatus.equals("102")) {
        drStatusView = Util.nvl(incdInfo.get("autocarDrivingStatusCdView"));
      } 
      row = sheet.createRow(8);
      row.setHeight((short)500);
      c_08_A = row.createCell(0);
      c_08_A.setCellStyle((CellStyle)style5);
      c_08_A.setCellValue("");
      c_08_B = row.createCell(1);
      c_08_B.setCellStyle((CellStyle)style5);
      c_08_B.setCellValue("");
      c_08_C = row.createCell(2);
      c_08_C.setCellStyle((CellStyle)style6);
      c_08_C.setCellValue(drStatusView);
      c_08_D = row.createCell(3);
      c_08_D.setCellStyle((CellStyle)style6);
      c_08_D.setCellValue("");
      c_08_E = row.createCell(4);
      c_08_E.setCellStyle((CellStyle)style6);
      c_08_E.setCellValue("");
      c_08_F = row.createCell(5);
      c_08_F.setCellStyle((CellStyle)style6);
      c_08_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(8, 8, 2, 5));
      int rideNum = Util.nvl(String.valueOf(incdInfo.get("autocarRideNumber")), 0);
      int loadVol = Util.nvl(String.valueOf(incdInfo.get("autocarLoadVol")), 0);
      String rideStr = ": " + rideNum + "/ : " + loadVol;
      row = sheet.createRow(9);
      row.setHeight((short)500);
      c_09_A = row.createCell(0);
      c_09_A.setCellStyle((CellStyle)style5);
      c_09_A.setCellValue("");
      c_09_B = row.createCell(1);
      c_09_B.setCellStyle((CellStyle)style5);
      c_09_B.setCellValue("");
      c_09_C = row.createCell(2);
      c_09_C.setCellStyle((CellStyle)style6);
      c_09_C.setCellValue(rideStr);
      c_09_D = row.createCell(3);
      c_09_D.setCellStyle((CellStyle)style6);
      c_09_D.setCellValue("");
      c_09_E = row.createCell(4);
      c_09_E.setCellStyle((CellStyle)style6);
      c_09_E.setCellValue("");
      c_09_F = row.createCell(5);
      c_09_F.setCellStyle((CellStyle)style6);
      c_09_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(9, 9, 2, 5));
      row = sheet.createRow(10);
      row.setHeight((short)500);
      c_10_A = row.createCell(0);
      c_10_A.setCellStyle((CellStyle)style5);
      c_10_A.setCellValue("");
      c_10_B = row.createCell(1);
      c_10_B.setCellStyle((CellStyle)style5);
      c_10_B.setCellValue("");
      c_10_C = row.createCell(2);
      c_10_C.setCellStyle((CellStyle)style6);
      c_10_C.setCellValue(Util.nvl(incdInfo.get("autocarDamageView")));
      c_10_D = row.createCell(3);
      c_10_D.setCellStyle((CellStyle)style6);
      c_10_D.setCellValue("");
      c_10_E = row.createCell(4);
      c_10_E.setCellStyle((CellStyle)style6);
      c_10_E.setCellValue("");
      c_10_F = row.createCell(5);
      c_10_F.setCellStyle((CellStyle)style6);
      c_10_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(10, 10, 2, 5));
      String auto_typ = Util.nvl(incdInfo.get("humanInjuryTypeView"));
      String auto_sex = Util.nvl(incdInfo.get("autocarHumanSexView"));
      int auto_age = Util.nvl(String.valueOf(incdInfo.get("autocarHumanAge")), 0);
      String auto_human = auto_typ + " / " + auto_sex + "  / " + auto_age;
      row = sheet.createRow(11);
      row.setHeight((short)500);
      c_11_A = row.createCell(0);
      c_11_A.setCellStyle((CellStyle)style5);
      c_11_A.setCellValue("");
      c_11_B = row.createCell(1);
      c_11_B.setCellStyle((CellStyle)style5);
      c_11_B.setCellValue("");
      c_11_C = row.createCell(2);
      c_11_C.setCellStyle((CellStyle)style6);
      c_11_C.setCellValue(auto_human);
      c_11_D = row.createCell(3);
      c_11_D.setCellStyle((CellStyle)style6);
      c_11_D.setCellValue("");
      c_11_E = row.createCell(4);
      c_11_E.setCellStyle((CellStyle)style6);
      c_11_E.setCellValue("");
      c_11_F = row.createCell(5);
      c_11_F.setCellStyle((CellStyle)style6);
      c_11_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(7, 11, 0, 0));
      sheet.addMergedRegion(new CellRangeAddress(11, 11, 2, 5));
      log.debug(" @@@@@@@@@@@@@@ : 5");
      int iRow = 12;
      for (int i = 0; i < carList.size(); i++) {
        Map<String, String> egovMap = (Map<String, String>)carList.get(i);
        String seq = String.valueOf(i + 1);
        String acc_drStatus = Util.nvl(String.valueOf(egovMap.get("acccarDrivingStatusCd")));
        String acc_drStatusView = "";
        if (acc_drStatus.equals("101")) {
          acc_drStatusView = Util.nvl(String.valueOf(egovMap.get("acccarDrivingStatusCdView"))) + "(" + String.valueOf(egovMap.get("acccarSpeed")) + " km/h)";
        } else if (acc_drStatus.equals("102")) {
          acc_drStatusView = Util.nvl(String.valueOf(egovMap.get("acccarDrivingStatusCdView")));
        } 
        int acc_rideNum = Util.nvl(String.valueOf(egovMap.get("acccarRideNumber")), 0);
        int acc_loadVol = Util.nvl(String.valueOf(egovMap.get("acccarLoadVol")), 0);
        String acc_rideStr = ": " + acc_rideNum + "/ : " + acc_loadVol;
        String acc_auto_typ = Util.nvl(String.valueOf(egovMap.get("humanInjuryTypeView")));
        String acc_auto_sex = Util.nvl(String.valueOf(egovMap.get("acccarHumanSexView")));
        int acc_auto_age = Util.nvl(String.valueOf(egovMap.get("acccarHumanAge")), 0);
        String acc_auto_human = acc_auto_typ + " / " + acc_auto_sex + "  / " + acc_auto_age;
        row = sheet.createRow(iRow);
        row.setHeight((short)500);
        XSSFCell c_R1_A = row.createCell(0);
        c_R1_A.setCellStyle((CellStyle)style5);
        c_R1_A.setCellValue(seq);
        XSSFCell c_R1_B = row.createCell(1);
        c_R1_B.setCellStyle((CellStyle)style5);
        c_R1_B.setCellValue("");
        XSSFCell c_R1_C = row.createCell(2);
        c_R1_C.setCellStyle((CellStyle)style6);
        c_R1_C.setCellValue(Util.nvl(String.valueOf(egovMap.get("acccarCarTypeView"))));
        XSSFCell c_R1_D = row.createCell(3);
        c_R1_D.setCellStyle((CellStyle)style6);
        c_R1_D.setCellValue("");
        XSSFCell c_R1_E = row.createCell(4);
        c_R1_E.setCellStyle((CellStyle)style6);
        c_R1_E.setCellValue("");
        XSSFCell c_R1_F = row.createCell(5);
        c_R1_F.setCellStyle((CellStyle)style6);
        c_R1_F.setCellValue("");
        sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 2, 5));
        iRow++;
        row = sheet.createRow(iRow);
        row.setHeight((short)500);
        XSSFCell c_R2_A = row.createCell(0);
        c_R2_A.setCellStyle((CellStyle)style5);
        c_R2_A.setCellValue("");
        XSSFCell c_R2_B = row.createCell(1);
        c_R2_B.setCellStyle((CellStyle)style5);
        c_R2_B.setCellValue("");
        XSSFCell c_R2_C = row.createCell(2);
        c_R2_C.setCellStyle((CellStyle)style6);
        c_R2_C.setCellValue(Util.nvl(String.valueOf(egovMap.get("acccarDrivingModeView"))));
        XSSFCell c_R2_D = row.createCell(3);
        c_R2_D.setCellStyle((CellStyle)style6);
        c_R2_D.setCellValue("");
        XSSFCell c_R2_E = row.createCell(4);
        c_R2_E.setCellStyle((CellStyle)style6);
        c_R2_E.setCellValue("");
        XSSFCell c_R2_F = row.createCell(5);
        c_R2_F.setCellStyle((CellStyle)style6);
        c_R2_F.setCellValue("");
        sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 2, 5));
        iRow++;
        row = sheet.createRow(iRow);
        row.setHeight((short)500);
        XSSFCell c_R3_A = row.createCell(0);
        c_R3_A.setCellStyle((CellStyle)style5);
        c_R3_A.setCellValue("");
        XSSFCell c_R3_B = row.createCell(1);
        c_R3_B.setCellStyle((CellStyle)style5);
        c_R3_B.setCellValue("");
        XSSFCell c_R3_C = row.createCell(2);
        c_R3_C.setCellStyle((CellStyle)style6);
        c_R3_C.setCellValue(acc_drStatusView);
        XSSFCell c_R3_D = row.createCell(3);
        c_R3_D.setCellStyle((CellStyle)style6);
        c_R3_D.setCellValue("");
        XSSFCell c_R3_E = row.createCell(4);
        c_R3_E.setCellStyle((CellStyle)style6);
        c_R3_E.setCellValue("");
        XSSFCell c_R3_F = row.createCell(5);
        c_R3_F.setCellStyle((CellStyle)style6);
        c_R3_F.setCellValue("");
        sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 2, 5));
        iRow++;
        row = sheet.createRow(iRow);
        row.setHeight((short)500);
        XSSFCell c_R4_A = row.createCell(0);
        c_R4_A.setCellStyle((CellStyle)style5);
        c_R4_A.setCellValue("");
        XSSFCell c_R4_B = row.createCell(1);
        c_R4_B.setCellStyle((CellStyle)style5);
        c_R4_B.setCellValue("");
        XSSFCell c_R4_C = row.createCell(2);
        c_R4_C.setCellStyle((CellStyle)style6);
        c_R4_C.setCellValue(acc_rideStr);
        XSSFCell c_R4_D = row.createCell(3);
        c_R4_D.setCellStyle((CellStyle)style6);
        c_R4_D.setCellValue("");
        XSSFCell c_R4_E = row.createCell(4);
        c_R4_E.setCellStyle((CellStyle)style6);
        c_R4_E.setCellValue("");
        XSSFCell c_R4_F = row.createCell(5);
        c_R4_F.setCellStyle((CellStyle)style6);
        c_R4_F.setCellValue("");
        sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 2, 5));
        iRow++;
        row = sheet.createRow(iRow);
        row.setHeight((short)500);
        XSSFCell c_R5_A = row.createCell(0);
        c_R5_A.setCellStyle((CellStyle)style5);
        c_R5_A.setCellValue("");
        XSSFCell c_R5_B = row.createCell(1);
        c_R5_B.setCellStyle((CellStyle)style5);
        c_R5_B.setCellValue("");
        XSSFCell c_R5_C = row.createCell(2);
        c_R5_C.setCellStyle((CellStyle)style6);
        c_R5_C.setCellValue(Util.nvl(String.valueOf(egovMap.get("acccarDamageView"))));
        XSSFCell c_R5_D = row.createCell(3);
        c_R5_D.setCellStyle((CellStyle)style6);
        c_R5_D.setCellValue("");
        XSSFCell c_R5_E = row.createCell(4);
        c_R5_E.setCellStyle((CellStyle)style6);
        c_R5_E.setCellValue("");
        XSSFCell c_R5_F = row.createCell(5);
        c_R5_F.setCellStyle((CellStyle)style6);
        c_R5_F.setCellValue("");
        sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 2, 5));
        iRow++;
        row = sheet.createRow(iRow);
        row.setHeight((short)500);
        XSSFCell c_R6_A = row.createCell(0);
        c_R6_A.setCellStyle((CellStyle)style5);
        c_R6_A.setCellValue("");
        XSSFCell c_R6_B = row.createCell(1);
        c_R6_B.setCellStyle((CellStyle)style5);
        c_R6_B.setCellValue("");
        XSSFCell c_R6_C = row.createCell(2);
        c_R6_C.setCellStyle((CellStyle)style6);
        c_R6_C.setCellValue(acc_auto_human);
        XSSFCell c_R6_D = row.createCell(3);
        c_R6_D.setCellStyle((CellStyle)style6);
        c_R6_D.setCellValue("");
        XSSFCell c_R6_E = row.createCell(4);
        c_R6_E.setCellStyle((CellStyle)style6);
        c_R6_E.setCellValue("");
        XSSFCell c_R6_F = row.createCell(5);
        c_R6_F.setCellStyle((CellStyle)style6);
        c_R6_F.setCellValue("");
        sheet.addMergedRegion(new CellRangeAddress(iRow - 5, iRow, 0, 0));
        sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 2, 5));
        iRow++;
      } 
      row = sheet.createRow(iRow);
      row.setHeight((short)2000);
      XSSFCell c_R7_A = row.createCell(0);
      c_R7_A.setCellStyle((CellStyle)style5);
      c_R7_A.setCellValue("");
      XSSFCell c_R7_B = row.createCell(1);
      c_R7_B.setCellStyle((CellStyle)style5);
      c_R7_B.setCellValue("");
      XSSFCell c_R7_C = row.createCell(2);
      c_R7_C.setCellStyle((CellStyle)style6);
      c_R7_C.setCellValue(Util.nvl(incdInfo.get("accDetailInfo")));
      XSSFCell c_R7_D = row.createCell(3);
      c_R7_D.setCellStyle((CellStyle)style6);
      c_R7_D.setCellValue("");
      XSSFCell c_R7_E = row.createCell(4);
      c_R7_E.setCellStyle((CellStyle)style6);
      c_R7_E.setCellValue("");
      XSSFCell c_R7_F = row.createCell(5);
      c_R7_F.setCellStyle((CellStyle)style6);
      c_R7_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 0, 1));
      sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 2, 5));
      iRow++;
      row = sheet.createRow(iRow);
      row.setHeight((short)2500);
      c_01_A = row.createCell(0);
      c_01_A.setCellStyle((CellStyle)style2);
      c_01_A.setCellValue("");
      c_01_B = row.createCell(1);
      c_01_B.setCellStyle((CellStyle)style2);
      c_01_B.setCellValue("");
      c_01_C = row.createCell(2);
      c_01_C.setCellStyle((CellStyle)style2);
      c_01_C.setCellValue("");
      c_01_D = row.createCell(3);
      c_01_D.setCellStyle((CellStyle)style2);
      c_01_D.setCellValue("");
      c_01_E = row.createCell(4);
      c_01_E.setCellStyle((CellStyle)style2);
      c_01_E.setCellValue("");
      c_01_F = row.createCell(5);
      c_01_F.setCellStyle((CellStyle)style2);
      c_01_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 0, 5));
      iRow++;
      row = sheet.createRow(iRow);
      row.setHeight((short)1000);
      c_01_A = row.createCell(0);
      c_01_A.setCellStyle((CellStyle)style2);
      c_01_A.setCellValue("");
      c_01_B = row.createCell(1);
      c_01_B.setCellStyle((CellStyle)style2);
      c_01_B.setCellValue("");
      c_01_C = row.createCell(2);
      c_01_C.setCellStyle((CellStyle)style2);
      c_01_C.setCellValue("");
      c_01_D = row.createCell(3);
      c_01_D.setCellStyle((CellStyle)style2);
      c_01_D.setCellValue("");
      c_01_E = row.createCell(4);
      c_01_E.setCellStyle((CellStyle)style2);
      c_01_E.setCellValue("");
      c_01_F = row.createCell(5);
      c_01_F.setCellStyle((CellStyle)style2);
      c_01_F.setCellValue("");
      sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 0, 1));
      sheet.addMergedRegion(new CellRangeAddress(iRow, iRow, 2, 5));
      FileOutputStream fileOutput = null;
      try {
        if (filePath == null || !"".equals(filePath));
        fileOutput = new FileOutputStream(filePath);
        wb.write(fileOutput);
      } catch (IOException iOException1) {
        IOException ioe = null;
        log.info("[IncdExcel Exception] 1: " + ioe.toString());
        result = "0";
      } finally {
        if (fileOutput != null)
          try {
            fileOutput.close();
          } catch (IOException iOException1) {
            IOException e1 = null;
            log.info("[IncdExcel fileOutput] : " + e1.toString());
          }  
      } 
    } catch (Exception e) {
      log.info("[IncdExcel Exception] 2: " + e.toString());
      result = "0";
    } 
    return result;
  }
}
